### ISSUE TITLE
Rozšírenie pre Safari

### ISSUE THREAD

**Issue by originalmagneto** [slovensko-digital/autogram-extension#75]
Chyba mi odkaz na Safari (macOS). Viem si to spraviť cez Xcode, ale bolo by fajn mat priamo odkaz aj na macOS Safari verziu (keďže Safari je najpoužívanejší browser na macOS)

**Comment by jsuchal** [comment]
@pomali tu nam co chyba na nejaky release?

**Comment by pomali** [comment]
asi zas tancek s gh actions, podpisovanim a s releaseom do app store-u

**Comment by pomali** [comment]
Urobil som experimentalny build pre safari, je nepodpisana takze bude potrebne povolit nepodpisane extensions 
https://developer.apple.com/documentation/safariservices/safari_web_extensions/running_your_safari_web_extension#3744467
(Settings > Advanced > "Show Develop menu in menu bar"; Develop menu > Allow Unsigned Extensions)

https://github.com/slovensko-digital/autogram-extension/releases/tag/v1.6.0

**Comment by jsuchal** [comment]
@pomali to podpisovanie je rovnako komplikovane ako pri autograme ci existuje nejaka gh action na toto?

**Comment by pomali** [comment]
Malo by to byť ľahšie, lebo všetko je natívny XCode

A v podstate by to mal byť rovnaký workflow ako pre ios appky, takze aj fastlane je možnosť

https://litoarias.medium.com/continuous-delivery-for-ios-using-fastlane-and-github-actions-edf62ee68ecc

**Comment by pomali** [comment]
https://slovensko-digital.slack.com/archives/C0564RNLT62/p1706616623676799

**Comment by originalmagneto** [comment]
Pokrocilo sa s tymto nejak?

**Comment by originalmagneto** [comment]
@pomali @celuchmarek Zdravím, je tu nejaký posun? Vdaka!

**Comment by originalmagneto** [comment]
Co to Safari? Dočkáme sa? 😬 Viem si predstaviť aby to tým pádom fungovalo aj v iOS/iPadOS v spolupráci s webovými aplikáciami bez potreby QR kódov a pod

**Comment by celuchmarek** [comment]
@originalmagneto už sa varí a pečie. Zdá sa, že máme funkčnú verziu pre Safari s podporou Autogramu aj AVM. Čaká sa na review v AppStore, ale teda v priebehu niekoľkých dní by mohol byť dostupný 😊

**Comment by celuchmarek** [comment]
Safari extension ale bude iba pre MacOS, čiže na iOS sa to nedá používať. V iOS vieš mať nainštalovaný AVM. QR kódu sa zbavíš, keď dorobíme notifikácie.

Vieme do budúcna experimentovať aj so Safari extension na iOS (taká vec existuje) - teoreticky by sa potom dalo aj priamo na mobile podpisovať na slovensko.sk 🤔 Ale to je nice-to-have

**Comment by celuchmarek** [comment]
Zdá sa, že Safari funguje ok. (Ak teda user nemá nejako divne ponastavovaný Mac OS, na ktorom si Autogram nevie vyrobiť SSL certifikáty - ale to doriešime na slacku, prípadne v Autogram potom fixneme)
