### ISSUE TITLE
Assety (texty/obrazky) do store-ov

### ISSUE THREAD

**Issue by pomali** [slovensko-digital/autogram-extension#9]
## Google Chrome
- [x] Title from package
- [x] Summary from package
- [x] Description
- [x] Category
- [ ] Store icon (img)
- [ ] (Global promo video (video))
- [ ] Screenshots (img x5)
- [ ] (Small/large/marquee promo tile)
- [ ] (Official URL)
- [ ] Homepage URL
- [ ] Support URL

## Mozilla Firefox
- [x] Name
- [x] Summary
- [ ] Description (250chars)
- [x] Categories
- [x] Email
- [ ] Website
- [ ] Addon icon (img)
- [ ] Screenshots (img x3)
- [ ] Homepage
- [ ] (Tags)

## Microsoft Edge
(more or less same as chrome)
- [ ] Screenshots (imgs)

## Apple Safari
???

**Comment by celuchmarek** [comment]
Toto už je imho bezpredmetné, už sme releasli niekoľko verzií a materiály v storoch sú dostatočné.
