### ISSUE TITLE
Extension sa mi neaktivuje na novej stránke formulárov ORSR - https://sluzby.orsr.sk/Sluzby/Zmena

### ISSUE THREAD

**Issue by originalmagneto** [slovensko-digital/autogram-extension#93]
Na novom webe aktualizovaných formulárov ORSR sa nespúšťa Autogram, ale starý štátny podpisovač. Zatiaľ som skúšal len Zápis zmien v ORSR, ale predpokladám, že to bude potrebné vyriešiť aj u ostatných nových formulárov. 

https://sluzby.orsr.sk/Sluzby

<img width="1042" alt="Screenshot 2024-06-25 at 09 57 05" src="https://github.com/slovensko-digital/autogram-extension/assets/15067415/dc414e9f-a3dc-459b-9be7-00799de0eead">

<img width="1042" alt="Screenshot 2024-06-25 at 09 58 57" src="https://github.com/slovensko-digital/autogram-extension/assets/15067415/236b4738-740d-4c83-b189-dbb65edab5b5">

<img width="912" alt="Screenshot 2024-06-25 at 10 00 25" src="https://github.com/slovensko-digital/autogram-extension/assets/15067415/e936e126-8c2c-4d21-944f-762e4ed24c0a">

**Comment by celuchmarek** [comment]
Už riešime v #94 . ORSR portál nebol zahrnutý, lebo tam trebalo trochu inak ten podpis robiť, ale už vieme, čo to bolo a je to pomerne jednoduché. Bude si treba ale aj updatnúť Autogram na v2.2.0 (comming soon).

**Comment by celuchmarek** [comment]
@originalmagneto Autogram extension v2.0.3 a Autogram v2.2.2 https://sluzby.slovensko.digital/autogram/#download dokopy prinášajú funkčnosť na sluzby.orsr.sk a opravujú použitie pri ORSR formulároch v prílohách na úpvs.
